apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-app
  labels:
    app: chain-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chain-app
  template:
    metadata:
      labels:
        app: chain-app
    spec:
      containers:
      - name: chain-deployment
        image: pradiplabade/chain-app
        ports:
        - containerPort: 80
