apiVersion: v1
kind: Service
metadata:
  name: chain-app
spec:
  selector:
    app: chain-app  # <-- must match pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # <-- needed for Kind access
